---
# Location where configuration files will be stored
config_dir: '~'

pihole_domain: 'pihole-1.starling-goldeye.ts.net'
pihole_local_ip: 127.0.0.1
pihole_local_port: 8080

tailscale_default_options_settings:
  # Allow caddy user to fetch cert.
  # See https://bit.ly/3Xm2ltA
  - regexp: "^#?TS_PERMIT_CERT_UID"
    line: "TS_PERMIT_CERT_UID=\"www-data\""
